spring:

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: tjMbWffexkyrVXSOUDhbEXPyPY4vD8ksN2Ro2q959RWfmEWw5HIYj8486zQVKxDWTnI9zjvFLmZTneEwNzBcIo
            redirect-uri: "http://localhost:8072/login/oauth2/code/keycloak"

        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/finance

  data:
    redis:
      host: redis

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
