server:
  port: 8072

spring:
  cloud:
    gateway:
      server:
        webflux:
          x-forwarded:
            enabled: true

          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true

          httpclient:
            connect-timeout: 1000000
            response-timeout: 20000s

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: finance
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

  data:
    redis:
      connect-timeout: 2s
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: gatewayserver
    description: Gateway Server Application
    version: 1.0.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

logging:
  level:
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.oauth2.jwt: TRACE
