server:
  port: 9000
  forward-headers-strategy: framework

  servlet:
    session:
      cookie:
        name: LOANS_SESSION

spring:
  jpa:
    show-sql: true

  sql:
    init:
      mode: always

info:
  app:
    name: loans
    description: Finance Application
